"""Added points column to user table

Revision ID: 485256e474e5
Revises: de6e1d76b23f
Create Date: 2024-07-10 03:20:19.815566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485256e474e5'
down_revision = 'de6e1d76b23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###
